### PR TITLE
Delete unmaintained wrappers

### PR DESCRIPTION
**Pull request by RasmusRendal**
These don't seem to have worked for years, so there is not much reason to keep them in main.

### CODE REVIEW

**Comment by yrke** [comment]
If it does not work we can remove, we also have copy in the historic repo

**Comment by mikucionisaau** [comment]
The wrappers are used in teaching to interact with DBMs via rubby scripts. 
At least it used to be part of verification course together with BDDs.
I think we need to rewrite the `Makefile`s into `CMakeLists.txt` instead of killing them. 
Swix is hard to get right as one has to accomodate multiple language bindings, I don't want to reengineer this.

**Comment by mikucionisaau** [comment]
I just checked it: it has been broken in 2017-18 and marinated in uppaal repo, because nobody cared to run the tests and it has not been published publically (the outside users used snapshots).
Basically this needs to be fixed (seems like most of the issues are trivial artefacts of find-and-replace spree) and not killed.

**Comment by mikucionisaau** [comment]
It seems that ruby/swix bindings/wrapper used to be distributed as a separate package on Alexandre's webpage (@yrke do you have a snapshot perhaps?).
Also the wrapper build scripts depend on the UDBM being already installed as is consults with `udbm-config` utility, which should be replaced with `find_udbm.cmake` scripts... there are also some strange ruby script which patch `Makefile`.
Overall, I think it would be best to move the wrapper files into separate project as it used to be published.

**Pull request merged**
